# Generated by Django 4.1.4 on 2023-01-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='headOfDepartmentn',
            new_name='headOfDepartment',
        ),
    ]
