# Generated by Django 4.1.4 on 2023-01-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_headofdepartmentn_departments_headofdepartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
