# Generated by Django 4.1.4 on 2023-01-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='hourPerWeek',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
