# Generated by Django 4.1.4 on 2023-01-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subject_credit_subject_hourperweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('emailId', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField(max_length=8)),
                ('yearOfAddmission', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.branch')),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.department'),
        ),
    ]
